databases:
  - db: SampleDB
    token: 1234567890
  - db: SampleDB2
    token: 1234567890
html_header: |
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>$qt_title</title>
      <style>
          body {
              font-family: Arial, Helvetica, sans-serif;
          }
          h1, h2, h3 {
              font-size: 16px;
          }
          table {
              border-collapse: collapse;
              width: 95%;
          }
          td, th {
              border: 1px solid #ddd;
              padding: 8px;
          }
          tr:nth-child(even){background-color: #f2f2f2;}
      </style>
  </head>
  <body>

html_footer: |
    <p>$qt_report_time</p>
  </body>
  </html>

section_header: |
  <h1>$qt_title</h1>

section_footer: |
  <p>$qt_note</p>

mail_from: albert_huang@unknown.com
mail_bcc: albert_huang@unknown.com
